print ("Welcome to tip calculator")
total = (input("What was the total bill? " ))
percent = (input("What percentage tip would youl like to give? "))
people = (input("How many people to split the bill? "))
print(f"Each person should pay: {round(((float(total) / float(people)) * (float(percent) / 100)) + (float(total) / float(people)),2)}")
